### ISSUE TITLE
Issue in installing Plugin [Plugin could not be activated because it triggered a fatal error.]

### ISSUE THREAD

**Issue by Somu60789** [oidc-wp/oidc-wp-roles#2]
Warning: require_once(/var/www/html/wp-content/plugins/oidc-wp-roles-main/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/oidc-wp-roles-main/oidc-wp-roles.php on line 25 Fatal error: Uncaught Error: Failed opening required '/var/www/html/wp-content/plugins/oidc-wp-roles-main/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/plugins/oidc-wp-roles-main/oidc-wp-roles.php:25 Stack trace: #0 /var/www/html/wp-includes/class-wp-hook.php(308): oidc_wp_roles_install('') #1 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #2 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #3 /var/www/html/wp-admin/plugins.php(194): do_action('activate_oidc-w...') #4 {main} thrown in /var/www/html/wp-content/plugins/oidc-wp-roles-main/oidc-wp-roles.php on line 25

**Comment by Somu60789** [comment]
I installed the wordpress using docker
